- type: include
  include: okko


- type: section
  section: body
  content:
    - type: node
      node: div
      attributes:
        class: content-class
        title: content-title
      content:
        - type: node
          node: span
          content: Show Me The Love
        - |
          <script src="123123"></script>
          @if($name == "123")
            echo "123123";
          @else
            as;dfjasdjf
          @endif

- type: push
  push: after-scripts
  content:
    - <script src="https://wwww.baidu.com/a.js"></script>
    - <script src="https://wwww.baidu.com/b.js"></script>


