<?php

namespace Tests\Unit;

use App\Models\Post\Type\Type;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class PostType extends TestCase
{
    use RefreshDatabase;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->refreshDatabase();
    }

    /** @test */
    public function create()
    {
        $type = new Type();
        $type->name = "Test Post Type";
        $result = $type->save();

        $this->assertTrue($result);
        $this->assertIsString($type->slug);
        $this->assertEquals(1, $type->order);
    }

    /** @test */
    public function checkOrderAdjust()
    {
        for ($i = 0; $i < 10; $i++) {
            $model = new Type();
            $model->name = "Test Post Type {$i}";
            $model->save();
        }

        /** @var Type $type */
        $type = Type::find(2);
        $type->moveToEnd();

        $this->assertEquals(Type::count(), $type->order);
    }
}
