<?php

namespace Tests\Unit;

use anlutro\LaravelSettings\DatabaseSettingStore;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class SettingTest extends TestCase
{
    use RefreshDatabase;

    /** @var DatabaseSettingStore */
    public $settingStore;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->refreshDatabase();

        $this->settingStore = app('setting');
//        dd(config('settings'));
    }


    /** @test */
    public function write()
    {
        $this->settingStore->set("aaa", 'aaa-value');
        $this->settingStore->set([
            'b' => 'b-value',
            'c' => 'c-value',
        ]);
        $this->settingStore->save();

        $this->assertTrue($this->settingStore->has("aaa"));
    }

    /** @test */
    public function has()
    {
        $this->assertTrue($this->settingStore->has("aaa"));
    }

    /** @test */
    public function get()
    {
        $result = $this->settingStore->get('aaa');
        $this->assertEquals('aaa-value', $result);
    }
}
